version: "2.2"
services:
  # 1. Message Broker
  zookeeper:
    image: 'zookeeper:3.5'
    ports:
      - "2181:2181"

  kafka:
    image: 'wurstmeister/kafka:2.12-2.2.1'
    ports:
      - "9092:9092"
    environment:
      # HOSTNAME_COMMAND is used to determine the IP, but here we enforce explicit listeners
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "transactions:1:1"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  # 2. The Flink Cluster
  jobmanager:
    image: flink:1.17-java11
    ports:
      - "8081:8081" # Flink Dashboard
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.17-java11
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 # Allow parallel processing

  # 3. Storage for Results
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"